name = "firefly-admin"
compatibility_date = "2024-09-23"
pages_build_output_dir = "public"

# 非敏感配置（敏感信息请用 `wrangler pages secret put` 设置，见 README）
[vars]
GH_OWNER = "slepoh"
GH_REPO = "Firefly"
GH_BRANCH = "master"
ADMIN_PASSWORD = "123456"
GITHUB_TOKEN = "github_pat_11AFLVVOI0fPyXmCRfOyR5_mgP6Ax8NRzQkbYX0lMyZOB97Z8BBLGfR4UEGKH74dRIX5SVu"
